### PR TITLE
Update to intellij 2023.3

### PR DESCRIPTION
**Pull request by Kuzat**

### CODE REVIEW

**Comment by SamJakob** [comment]
Thanks!

**Comment by Kuzat** [comment]
I guess you would have to run the script to publish the new build to Intllij marketplace and such?

**Comment by SamJakob** [comment]
Yes, I hadn't had time to do that yet but will do today.

**Comment by SamJakob** [comment]
Hey, sorry for the delay. The new version 2023.3 has been submitted to the Marketplace for approval.

**Pull request merged**
